# Generated by Django 5.1.4 on 2025-01-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(default='No details available'),
        ),
    ]
