# Generated by Django 5.1.4 on 2025-01-05 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_product_description_product_details'),
        ('home', '0003_enquiry_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='product_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.productline'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
