# Generated by Django 5.1.4 on 2024-12-30 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
